In [1]:

import numpy as np

# Numpy Arrays
Nump arrays come in 2 flavours:
- 1D Vector arrays
- 2D Matrices


In [6]:
my_list = [1,2,3]
arr = np.array(my_list)
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
my_mat = np.array(my_mat)
my_mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Most common way to create numpy arrays is with `np.arange()`

In [9]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])